version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - REACT_APP_API_URL=http://${API_HOSTNAME}:${API_PORT}
    volumes:
      - ./frontend:/app
      - /app/node_modules

  api:
    build: ./api
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - PORT=${API_PORT}
      - BACKEND_URL=http://${BACKEND_HOSTNAME}:${BACKEND_PORT}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./backend/scripts:/app/backend/scripts

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - PORT=${BACKEND_PORT}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./logs:/app/logs

volumes:
  logs:
