version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://api:3001
      - REACT_APP_BACKEND_URL=http://backend:5000
    depends_on:
      - api
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env

  api:
    build: ./api
    ports:
      - "3001:3001"
    volumes:
      - ./backend/scripts:/app/scripts
