version: '3.8'

services:
  frontend:
    build: ./frontend
    hostname: ${FRONTEND_HOSTNAME}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    env_file:
      - .env
    networks:
      - app-network

  api:
    build: ./api
    hostname: ${API_HOSTNAME}
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - BACKEND_URL=http://backend:5000
    env_file:
      - .env
    networks:
      - app-network

  backend:
    build: ./backend
    hostname: ${BACKEND_HOSTNAME}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
